import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    // Home
    { url: "https://ceres-revops.fr", lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    // Services
    { url: "https://ceres-revops.fr/audit-revops", lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: "https://ceres-revops.fr/revops-part-time", lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: "https://ceres-revops.fr/agence-hubspot", lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: "https://ceres-revops.fr/agents-ia", lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    // Ressources
    { url: "https://ceres-revops.fr/revops", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://ceres-revops.fr/blog", lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    // Blog articles
    { url: "https://ceres-revops.fr/blog/emelia-test-outil-cold-emailing", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/tracking-conversions-hubspot-guide-complet", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/comparatif-outils-generation-leads-enrichissement", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/account-based-marketing-guide", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/integration-hubspot-whatsapp", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/hublead-linkedin-hubspot", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/marketing-automation-7-workflows-hubspot", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/meilleures-pratiques-sequences-hubspot", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/gerer-mrr-revenu-recurrent-hubspot", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/9-actions-commerciales-automatiser-hubspot", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/skag-single-keyword-ad-group-google-ads", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/cimetieres-startups-modeles-saas-b2b", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/marketing-saas-b2b-15-questions-strategiques", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/tracker-soumissions-formulaire-hubspot-google-analytics-google-tag-manager", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/hubspot-cms-fondamentaux-site-internet-performant", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/hubspot-vs-pipedrive-comparatif-prix-fonctionnalites", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/integration-hubspot-calendly", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/tofu-mofu-bofu-strategie-inbound", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/cest-quoi-acquisition-marketing", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: "https://ceres-revops.fr/blog/crm-pme-2026", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/meilleur-crm-b2b-france", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/hubspot-tarifs-prix-2026", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://ceres-revops.fr/blog/hubspot-vs-salesforce-comparatif", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://ceres-revops.fr/blog/lead-scoring-guide-complet", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/kpi-commerciaux-indicateurs-vente", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/ia-processus-commercial-vente-b2b", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/migration-crm-guide-complet", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/aligner-marketing-sales-revops", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/data-quality-crm-audit-nettoyage", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/onboarding-hubspot-30-premiers-jours", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/claude-vs-chatgpt-equipes-commerciales", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/lemlist-test-complet-outil-prospection", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/top-agences-revops-france", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://ceres-revops.fr/blog/revops-manager-fiche-poste-salaire-competences", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/revops-vs-sales-ops-marketing-ops", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/stack-technologique-revops-2026", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/audit-revops-checklist-complete", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://ceres-revops.fr/blog/revops-10-quick-wins-30-jours", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/forecasting-commercial-methodes-outils", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/sla-marketing-sales-template", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/revops-startups-par-ou-commencer", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/metriques-revops-indicateurs-performance", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/blog/structurer-equipe-revops", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/guides", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/guide-revops-ultime", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://ceres-revops.fr/guide-revops-ultime/contenu", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/guide-ia-commercial", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://ceres-revops.fr/guide-ia-commercial/contenu", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://ceres-revops.fr/glossaire", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    // Other
    { url: "https://ceres-revops.fr/cas-clients", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
  ];
}
